//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banka()
        {
            this.BankaSube = new HashSet<BankaSube>();
        }
    
        public int BankaID { get; set; }
        public string BankaAd { get; set; }
        public string BankaKodu { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public string Faks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankaSube> BankaSube { get; set; }
    }
}
