//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapHareket
    {
        public int HesapHareketID { get; set; }
        public int HesapId { get; set; }
        public decimal IslemTutari { get; set; }
        public int IslemTurId { get; set; }
        public string IslemYonu { get; set; }
        public string IslemAciklamasi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual IslemTur IslemTur { get; set; }
        public virtual Hesap Hesap { get; set; }
    }
}
