//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hesap()
        {
            this.HesapHareket = new HashSet<HesapHareket>();
            this.ParaTransfer = new HashSet<ParaTransfer>();
        }
    
        public int HesapID { get; set; }
        public int BankaMusteriId { get; set; }
        public int HesapTurId { get; set; }
        public string HesapAd { get; set; }
        public string HesapNo { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> AcilisTarihi { get; set; }
        public Nullable<System.DateTime> KapanisTarihi { get; set; }
        public bool Aktif { get; set; }
        public decimal Bakiye { get; set; }
    
        public virtual BankaMusteri BankaMusteri { get; set; }
        public virtual HesapTur HesapTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapHareket> HesapHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParaTransfer> ParaTransfer { get; set; }
    }
}
