//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciTCNO { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public int KullaniciRolId { get; set; }
        public string GirisAd { get; set; }
        public string GirisSifre { get; set; }
        public Nullable<int> BankaSubeId { get; set; }
        public string Gorev { get; set; }
    
        public virtual BankaSube BankaSube { get; set; }
        public virtual KullaniciRol KullaniciRol { get; set; }
    }
}
