//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniBankaEntities : DbContext
    {
        public MiniBankaEntities()
            : base("name=MiniBankaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<BankaMusteri> BankaMusteri { get; set; }
        public virtual DbSet<BankaSube> BankaSube { get; set; }
        public virtual DbSet<HesapHareket> HesapHareket { get; set; }
        public virtual DbSet<HesapTur> HesapTur { get; set; }
        public virtual DbSet<IslemTur> IslemTur { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<ParaTransfer> ParaTransfer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vKullanici> vKullanici { get; set; }
        public virtual DbSet<Hesap> Hesap { get; set; }
        public virtual DbSet<vMusteri> vMusteri { get; set; }
    }
}
