//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParaTransfer
    {
        public int ParaTransferID { get; set; }
        public int HesapId { get; set; }
        public string AliciHesapIBAN { get; set; }
        public string AliciHesapBankaKodu { get; set; }
        public string AliciHesapBankaSubeKodu { get; set; }
        public string AliciHesapNo { get; set; }
        public string AliciAdSoyad { get; set; }
        public string TransferTurAd { get; set; }
        public decimal IslemTutari { get; set; }
        public string IslemAciklamasi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual Hesap Hesap { get; set; }
    }
}
