//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciTCNO { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public int KullaniciRolId { get; set; }
        public string KullaniciRolAd { get; set; }
        public string KullaniciRolKod { get; set; }
        public string GirisAd { get; set; }
        public string GirisSifre { get; set; }
        public Nullable<int> BankaSubeId { get; set; }
        public Nullable<int> BankaId { get; set; }
        public string BankaAd { get; set; }
        public string BankaKodu { get; set; }
        public string BankaSubeAd { get; set; }
        public string BankaSubeKodu { get; set; }
        public string Gorev { get; set; }
    }
}
